title:  Rashmeen Malhotra 
logo: /assets/img/ProfilePic.jpeg

description:
  <p align="center">
  <a href=https://rashmeenmalhotra.github.io/portfolio/">Github</a> |
  <a href="https://www.linkedin.com/in/rashmeen-malhotra-a3756616a/">LinkedIn</a> |
 
  <br>   
  I'm persuing Masters in Data Science- ML and AI
  <br>
  </p>

theme: jekyll-theme-minimal
